# Generated by Django 5.1.2 on 2024-10-26 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rule_app', '0002_rule_combined_rule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule',
            old_name='combined_rule',
            new_name='rule',
        ),
    ]
